// <auto-generated />
using BankAccountSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAccountSystem.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class BankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("BankAccountSystem.Models.Account", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("Agency")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Number");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("AccountType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BankAccountSystem.Models.CheckingAccount", b =>
                {
                    b.HasBaseType("BankAccountSystem.Models.Account");

                    b.Property<decimal>("Limit")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Checking");
                });

            modelBuilder.Entity("BankAccountSystem.Models.SavingsAccount", b =>
                {
                    b.HasBaseType("BankAccountSystem.Models.Account");

                    b.Property<int>("AnniversaryDay")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Savings");
                });
#pragma warning restore 612, 618
        }
    }
}
